spring:
  application:
    name: hrms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.12:5432/hrms
    username: postgres
    password: postgres
server:
  port: 8080
  max-http-request-header-size: 400000
mybatis:
  mapper-locations: classpath:mappers/*.xml

