spring:
  application:
    name: hrms
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  mybatis:
    mapper-locations: classpath:mappers/*.xml
server:
  max-http-header-size: 400000
  port: 8080


